name: run-docker-script

on:
    workflow_dispatch:
jobs:
    run-container:
        runs-on: ubuntu-latest
        steps:
          - name: run-docker-script
            run: |
                docker run --rm ghcr.io/alexlopex03/tor-engine-releases-web-hook
